mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/performance?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
#        format_sql: true
        default_batch_fetch_size: 100
#    hibernate:
#      ddl-auto: create

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hivernate.type: trace